######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 2 03:43:10 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += addinfo.h mainwindow.h
FORMS += addinfo.ui mainwindow.ui
SOURCES += addinfo.cpp main.cpp mainwindow.cpp
